/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import DB.DBConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author JoeAlpha
 */
public class Page3_Register extends javax.swing.JFrame {

    /**
     * Creates new form Page1_Login
     */
    public Page3_Register() {
        initComponents();
        
        // center the form
        this.setLocationRelativeTo(this);
        
        // creating button group for gender radio buttons
        ButtonGroup bgGroup = new ButtonGroup();
        bgGroup.add(btnMale);
        bgGroup.add(btnFemale);
    }
    
    // create a variable for connection to the database     
    PreparedStatement sqlQueryCheck;     
    PreparedStatement sqlQueryInsert;
    ResultSet res;
    Connection conn;
    
    // function of clearing the form
    private void clear_form() {
        txtFname.setText("");
        errorFname.setText(null);
        if(txtFname.getText().trim().equals("")){
            txtFname.setText("first name");
            txtFname.setForeground(Color.gray);
            FnameLine.setBackground(Color.black);
        }
        
        txtLname.setText("");
        errorLname.setText(null);
        if(txtLname.getText().trim().equals("")){
            txtLname.setText("last name");
            txtLname.setForeground(Color.gray);
            LnameLine.setBackground(Color.black);
        }
        
        txtPhone.setText("");
        errorPhone.setText(null);
        if(txtPhone.getText().trim().equals("")){
            txtPhone.setText("07xxxxxxxx");
            txtPhone.setForeground(Color.gray);
            PhoneLine.setBackground(Color.black);
        }
        
        txtEmail.setText("");
        errorEmail.setText(null);
        if(txtEmail.getText().trim().equals("")){
            txtEmail.setText("someone@newmail.com");
            txtEmail.setForeground(Color.gray);
            EmailLine.setBackground(Color.black);
        }
        
        txtPassword.setText("");
        errorPassword.setText(null);
        if(txtPassword.getText().trim().equals("")){
            txtPassword.setText("yourpassword");
            txtPassword.setForeground(Color.gray);
            PasswordLine.setBackground(Color.black);
        }
        
        txtConfirm.setText("");
        if(txtConfirm.getText().trim().equals("")){
            txtConfirm.setText("yourpassword");
            txtConfirm.setForeground(Color.gray);
            ConfirmLine.setBackground(Color.black);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        LnameLine = new javax.swing.JLabel();
        errorLname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        FnameLine = new javax.swing.JLabel();
        errorFname = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        EmailLine = new javax.swing.JLabel();
        errorEmail = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnFemale = new javax.swing.JRadioButton();
        btnMale = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        PhoneLine = new javax.swing.JLabel();
        errorPhone = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        PasswordLine = new javax.swing.JLabel();
        errorPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jPanel9 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        ConfirmLine = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JPasswordField();
        btnClear = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        redirectToLogin = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setOpaque(false);
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cover page.png"))); // NOI18N
        jPanel27.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 320, 320));

        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 320));

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setOpaque(false);
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 20)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.textHighlight);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Java Authentication System");
        jPanel28.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 390, 50));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        txtLname.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtLname.setForeground(java.awt.Color.gray);
        txtLname.setText("last name");
        txtLname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtLname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLnameFocusLost(evt);
            }
        });
        txtLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLnameKeyReleased(evt);
            }
        });
        jPanel2.add(txtLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        LnameLine.setBackground(java.awt.Color.darkGray);
        LnameLine.setOpaque(true);
        jPanel2.add(LnameLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        errorLname.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorLname.setForeground(java.awt.Color.red);
        jPanel2.add(errorLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 160, -1));

        jPanel28.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 170, 50));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Create new Account");
        jPanel28.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 390, 30));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user.png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        txtFname.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtFname.setForeground(java.awt.Color.gray);
        txtFname.setText("first name");
        txtFname.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtFname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFnameFocusLost(evt);
            }
        });
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFnameKeyReleased(evt);
            }
        });
        jPanel4.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        FnameLine.setBackground(java.awt.Color.darkGray);
        FnameLine.setOpaque(true);
        jPanel4.add(FnameLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        errorFname.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorFname.setForeground(java.awt.Color.red);
        jPanel4.add(errorFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 160, -1));

        jPanel28.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, 50));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Email Icon.png"))); // NOI18N
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 30, 30));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEmail.setForeground(java.awt.Color.gray);
        txtEmail.setText("someone@newmail.com");
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel5.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 300, 27));

        EmailLine.setBackground(java.awt.Color.darkGray);
        EmailLine.setOpaque(true);
        jPanel5.add(EmailLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 360, 1));

        errorEmail.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorEmail.setForeground(java.awt.Color.red);
        jPanel5.add(errorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 340, -1));

        jPanel28.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 360, 50));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFemale.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnFemale.setText("Female");
        btnFemale.setOpaque(false);
        jPanel6.add(btnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 6, -1, -1));

        btnMale.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnMale.setSelected(true);
        btnMale.setText("Male");
        btnMale.setOpaque(false);
        jPanel6.add(btnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 6, -1, -1));

        jPanel28.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 170, 40));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/phone.png"))); // NOI18N
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPhone.setForeground(java.awt.Color.gray);
        txtPhone.setText("07xxxxxxxx");
        txtPhone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPhone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPhoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPhoneFocusLost(evt);
            }
        });
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });
        jPanel7.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        PhoneLine.setBackground(java.awt.Color.darkGray);
        PhoneLine.setOpaque(true);
        jPanel7.add(PhoneLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        errorPhone.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorPhone.setForeground(java.awt.Color.red);
        jPanel7.add(errorPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 160, -1));

        jPanel28.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 170, 50));

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock.png"))); // NOI18N
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        PasswordLine.setBackground(java.awt.Color.darkGray);
        PasswordLine.setOpaque(true);
        jPanel8.add(PasswordLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        errorPassword.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        errorPassword.setForeground(java.awt.Color.red);
        jPanel8.add(errorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 160, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtPassword.setForeground(java.awt.Color.gray);
        txtPassword.setText("yourpassword");
        txtPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });
        jPanel8.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        jPanel28.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 170, 50));

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock.png"))); // NOI18N
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        ConfirmLine.setBackground(java.awt.Color.darkGray);
        ConfirmLine.setOpaque(true);
        jPanel9.add(ConfirmLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 170, 1));

        txtConfirm.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtConfirm.setForeground(java.awt.Color.gray);
        txtConfirm.setText("yourpassword");
        txtConfirm.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmFocusLost(evt);
            }
        });
        jPanel9.add(txtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 120, 27));

        jPanel28.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 170, 50));

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel28.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 90, 30));

        btnSignUp.setBackground(java.awt.SystemColor.textHighlight);
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSignUp.setForeground(java.awt.Color.white);
        btnSignUp.setText("Sign Up");
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel28.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 90, 30));

        redirectToLogin.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        redirectToLogin.setForeground(java.awt.SystemColor.textHighlight);
        redirectToLogin.setText("Already a member?  Login");
        redirectToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        redirectToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redirectToLoginMouseClicked(evt);
            }
        });
        jPanel28.add(redirectToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, 20));

        jPanel26.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 390, 380));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setOpaque(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel26.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 1, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // exit the system
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        lblExit.setForeground(Color.white);
        lblExit.setBackground(Color.red);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        lblExit.setForeground(Color.black);
        lblExit.setBackground(Color.white);
    }//GEN-LAST:event_lblExitMouseExited

    private void redirectToLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redirectToLoginMouseClicked
        // redirect to register page if you dont have an account already
        Page1_Login login = new Page1_Login();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_redirectToLoginMouseClicked

    /**
     * FORM VALIDATION
     */
    private void txtFnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnameFocusGained
        if(txtFname.getText().trim().toLowerCase().equals("first name")){
            txtFname.setText("");
            txtFname.setForeground(Color.black);
            FnameLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtFnameFocusGained

    private void txtFnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFnameFocusLost
        if(txtFname.getText().trim().equals("") || txtFname.getText().trim().equals("first name")){
            txtFname.setText("first name");
            txtFname.setForeground(Color.gray);
            FnameLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtFnameFocusLost

    private void txtFnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyReleased
        // validate the input of this field
        String PATTERN = "^[a-z A-Z]{0,30}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtFname.getText());

        if(!match.matches()) {
            errorFname.setText("Invalid first name!");
        } else {
            errorFname.setText(null);
        }
    }//GEN-LAST:event_txtFnameKeyReleased

    private void txtLnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLnameFocusGained
        if(txtLname.getText().trim().toLowerCase().equals("last name")){
            txtLname.setText(""); 
            txtLname.setForeground(Color.black);
            LnameLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtLnameFocusGained

    private void txtLnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLnameFocusLost
        if(txtLname.getText().trim().equals("") || txtLname.getText().trim().equals("last name")){
            txtLname.setText("last name");
            txtLname.setForeground(Color.gray);
            LnameLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtLnameFocusLost

    private void txtLnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLnameKeyReleased
        // validate the input of this field
        String PATTERN = "^[a-z A-Z]{0,30}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtLname.getText());

        if(!match.matches()) {
            errorLname.setText("Invalid last name!");
        } else {
            errorLname.setText(null);
        }
    }//GEN-LAST:event_txtLnameKeyReleased

    private void txtPhoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusGained
        if(txtPhone.getText().trim().toLowerCase().equals("07xxxxxxxx")){
            txtPhone.setText(""); 
            txtPhone.setForeground(Color.black);
            PhoneLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtPhoneFocusGained

    private void txtPhoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPhoneFocusLost
        if(txtPhone.getText().trim().equals("") || txtPhone.getText().trim().equals("07xxxxxxxx")){
            txtPhone.setText("07xxxxxxxx");
            txtPhone.setForeground(Color.gray);
            PhoneLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtPhoneFocusLost

    private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
        // validate the input of this field
        String PATTERN = "^[0-9 0-9]{0,10}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtPhone.getText());

        if(!match.matches()) {
            errorPhone.setText("Invalid phonenumber!");
        } else {
            errorPhone.setText(null);
        }
    }//GEN-LAST:event_txtPhoneKeyReleased

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        if(txtEmail.getText().trim().toLowerCase().equals("someone@newmail.com")){
            txtEmail.setText(""); 
            txtEmail.setForeground(Color.black);
            EmailLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(txtEmail.getText().trim().equals("") || txtEmail.getText().trim().equals("someone@newmail.com")){
            txtEmail.setText("someone@newmail.com");
            txtEmail.setForeground(Color.gray);
            EmailLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // validating email field to ensure (@) and (.) symbol are not ommitted
        String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{1,10}[.][a-zA-Z0-9]{2,5}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtEmail.getText());

        if(!match.matches()) {
            errorEmail.setText("Invalid email address!");
        } else {
            errorEmail.setText(null);
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        if(txtPassword.getText().trim().toLowerCase().equals("yourpassword")){
            txtPassword.setText(""); 
            txtPassword.setForeground(Color.black);
            PasswordLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if(txtPassword.getText().trim().equals("") || txtPassword.getText().trim().equals("yourpassword")){
            txtPassword.setText("yourpassword");
            txtPassword.setForeground(Color.gray);
            PasswordLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        String PATTERN = "^[a-zA-Z0-9_!@#$%^&*-?]{10,30}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtPassword.getText());

        if(!match.matches()) {
            errorPassword.setText("Invalid Password/Its too short!");
        } else {
            errorPassword.setText(null);
        }
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmFocusGained
        if(txtConfirm.getText().trim().toLowerCase().equals("yourpassword")){
            txtConfirm.setText(""); 
            txtConfirm.setForeground(Color.black);
            ConfirmLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtConfirmFocusGained

    private void txtConfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmFocusLost
        if(txtConfirm.getText().trim().equals("") || txtConfirm.getText().trim().equals("yourpassword")){
            txtConfirm.setText("yourpassword");
            txtConfirm.setForeground(Color.gray);
            ConfirmLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtConfirmFocusLost

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // operation of createing a new account
        String status   = "Offline";
        String first    = txtFname.getText();
        String last     = txtLname.getText();
        String phone    = txtPhone.getText();
        String gender   = "Male";
        if(btnFemale.isSelected()) { gender  = "Female"; }
        String email    = txtEmail.getText();
        String password = txtPassword.getText();
        String confirm  = txtConfirm.getText();
        
        // checking if any field is empty before submitting the form
        if(first.trim().equals("") || first.trim().equals("first name")){
            errorFname.setText("first name is empty!");
        } 
        else if(last.trim().equals("") || last.trim().equals("last name")){
            errorLname.setText("last name is empty!");
        }
        else if(phone.trim().equals("") || phone.trim().equals("07xxxxxxxx")){
            errorPhone.setText("phonenumber is empty!");
        }
        else if(email.trim().equals("") || email.trim().equals("someone@newmail.com")){
            errorEmail.setText("Email is empty!");
        }
        else if(password.trim().equals("") || password.trim().equals("yourpassword")){
            errorPassword.setText("password is empty!");
        }
        else if (password.equals(confirm)) {
            try {
                // conform if cridentials used already exist in the Database
                conn = DBConnection.setConnection();
                sqlQueryCheck = conn.prepareStatement("select * from tbl_users where phone=? or email=? ");
                sqlQueryCheck.setString(1, phone);
                sqlQueryCheck.setString(2, email);
                res = sqlQueryCheck.executeQuery();
                
                if(res.isBeforeFirst()) {
                    // if the credential already exist display error message
                    JOptionPane.showMessageDialog(this, "These Cridentials have been used by another User", "Please use new Cridentials", JOptionPane.ERROR_MESSAGE);

                    // clearing neccessary fields to allow the admin to re-enter new Cridentials
                    clear_form();
                }
                else {
                    sqlQueryInsert = conn.prepareStatement("insert into tbl_users (status,firstname,lastname,phone,gender,email,password) values (?,?,?,?,?,?,?) ");
                    sqlQueryInsert.setString(1, status);
                    sqlQueryInsert.setString(2, first);
                    sqlQueryInsert.setString(3, last);
                    sqlQueryInsert.setString(4, phone);
                    sqlQueryInsert.setString(5, gender);
                    sqlQueryInsert.setString(6, email);
                    sqlQueryInsert.setString(7, password);
                    
                    //if the record is inserted successfully the state of executeUpdate() will be 1
                    if (sqlQueryInsert.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "You account has been created successfully.");

                        // clearing the form after successfully adding the new record in the database
                        clear_form();

                        // redirect the user to security quiz page
                        new Page4_SecurityQuiz().setVisible(true);
                        this.dispose();

                        return;
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(Page3_Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Confirm Password doesn't match with Password!", "Please Try again", JOptionPane.ERROR_MESSAGE);
            txtConfirm.setText("");
            if(txtConfirm.getText().trim().equals("")){
                txtConfirm.setText("yourpassword");
                txtConfirm.setForeground(Color.gray);
                ConfirmLine.setBackground(Color.black);
            }
        
            return;
        }
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // operation for reseting account form
        clear_form();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page3_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page3_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page3_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page3_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page3_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmLine;
    private javax.swing.JLabel EmailLine;
    private javax.swing.JLabel FnameLine;
    private javax.swing.JLabel LnameLine;
    private javax.swing.JLabel PasswordLine;
    private javax.swing.JLabel PhoneLine;
    private javax.swing.JButton btnClear;
    private javax.swing.JRadioButton btnFemale;
    private javax.swing.JRadioButton btnMale;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel errorEmail;
    private javax.swing.JLabel errorFname;
    private javax.swing.JLabel errorLname;
    private javax.swing.JLabel errorPassword;
    private javax.swing.JLabel errorPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel redirectToLogin;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}