/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import DB.DBConnection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author JoeAlpha
 */
public class Page2_ResetPass extends javax.swing.JFrame {

    /**
     * Creates new form Page1_Login
     */
    public Page2_ResetPass() {
        initComponents();
                
        jLabel14.setVisible(false);
        jPanel30.setVisible(false);
        btnNext.setVisible(false);
        jLabel22.setVisible(false);
        jPanel10.setVisible(false);
        jLabel9.setVisible(false);
        jPanel8.setVisible(false);
        btnResetPwd.setVisible(false);
        
        // center the form
        this.setLocationRelativeTo(this);
    }
    
    // create a variable for connection to the database     
    PreparedStatement sqlQueryCheck;      
    PreparedStatement sqlQueryUpdate;   
    PreparedStatement sqlQueryLogin;
    ResultSet res;
    Connection conn;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel26 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        emailLine = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtTypeHere = new javax.swing.JTextField();
        quizLine = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnVerify = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        PasswordLine1 = new javax.swing.JLabel();
        pwdError1 = new javax.swing.JLabel();
        txtNewPwd = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        PasswordLine2 = new javax.swing.JLabel();
        pwdError2 = new javax.swing.JLabel();
        txtConfirmPwd = new javax.swing.JPasswordField();
        btnResetPwd = new javax.swing.JButton();
        lblExit = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setOpaque(false);
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 20)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.textHighlight);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Java Authentication System");
        jPanel28.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 350, 50));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reset Password");
        jPanel28.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 350, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(java.awt.SystemColor.windowBorder);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Enter the email recognized by this system");

        jPanel31.setOpaque(false);
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(java.awt.Color.gray);
        txtEmail.setText("someone@newmail.com");
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtEmail.setOpaque(false);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel31.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, 220, 40));

        emailLine.setBackground(java.awt.Color.darkGray);
        emailLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel31.add(emailLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 280, 1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Email Icon.png"))); // NOI18N
        jPanel31.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 30, 38));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(java.awt.SystemColor.windowBorder);
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Enter the answer for this security question ");

        jPanel30.setOpaque(false);
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/list.png"))); // NOI18N
        jPanel30.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 30, 38));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Which year and month were you born");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 1, 1));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel30.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 240, 70));

        txtTypeHere.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTypeHere.setForeground(java.awt.Color.gray);
        txtTypeHere.setText("type here");
        txtTypeHere.setBorder(null);
        txtTypeHere.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTypeHereFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTypeHereFocusLost(evt);
            }
        });
        jPanel30.add(txtTypeHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 230, 25));

        quizLine.setBackground(java.awt.Color.darkGray);
        quizLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel30.add(quizLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 106, 245, 1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnNext.setText("Next");
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnVerify.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnVerify.setText("Verify Email");
        btnVerify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setOpaque(false);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(java.awt.SystemColor.windowBorder);
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("New Password:");

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock.png"))); // NOI18N
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        PasswordLine1.setBackground(java.awt.Color.darkGray);
        PasswordLine1.setOpaque(true);
        jPanel10.add(PasswordLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 220, 1));

        pwdError1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pwdError1.setForeground(java.awt.Color.red);
        jPanel10.add(pwdError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 200, 16));

        txtNewPwd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtNewPwd.setForeground(java.awt.Color.gray);
        txtNewPwd.setText("yourpassword");
        txtNewPwd.setBorder(null);
        txtNewPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewPwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewPwdFocusLost(evt);
            }
        });
        txtNewPwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNewPwdKeyReleased(evt);
            }
        });
        jPanel10.add(txtNewPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 160, 27));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(java.awt.SystemColor.windowBorder);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Confirm Password:");

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Lock.png"))); // NOI18N
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        PasswordLine2.setBackground(java.awt.Color.darkGray);
        PasswordLine2.setOpaque(true);
        jPanel8.add(PasswordLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 220, 1));

        pwdError2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        pwdError2.setForeground(java.awt.Color.red);
        jPanel8.add(pwdError2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 34, 200, 16));

        txtConfirmPwd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtConfirmPwd.setForeground(java.awt.Color.gray);
        txtConfirmPwd.setText("yourpassword");
        txtConfirmPwd.setBorder(null);
        txtConfirmPwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmPwdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmPwdFocusLost(evt);
            }
        });
        jPanel8.add(txtConfirmPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 3, 160, 27));

        btnResetPwd.setBackground(java.awt.SystemColor.textHighlight);
        btnResetPwd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnResetPwd.setForeground(java.awt.Color.white);
        btnResetPwd.setText("Reset");
        btnResetPwd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPwdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 79, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnResetPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnResetPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 360, 310));

        jPanel28.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 340, 280));

        jPanel26.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 350, 340));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setOpaque(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel26.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 1, 30, -1));

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setOpaque(false);
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cover page.png"))); // NOI18N
        jPanel27.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 320, 320));

        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // exit the system
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        lblExit.setForeground(Color.white);
        lblExit.setBackground(Color.red);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        lblExit.setForeground(Color.black);
        lblExit.setBackground(Color.white);
    }//GEN-LAST:event_lblExitMouseExited

    /**
     * Email validation
     */
    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // operation that occur when this field is clicked
        if(txtEmail.getText().trim().toLowerCase().equals("someone@newmail.com")){
            txtEmail.setText("");
            txtEmail.setForeground(Color.black);
            emailLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // operation that occur when this field is not clicked
        if(txtEmail.getText().trim().equals("") || txtEmail.getText().trim().equals("someone@newmail.com")){
            txtEmail.setText("someone@newmail.com");
            txtEmail.setForeground(Color.gray);
            emailLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String email = txtEmail.getText();
            
            try {
                // checking if user credential already exist
                Connection conn = DBConnection.setConnection();
                sqlQueryCheck = conn.prepareStatement("select * from tbl_users where email=?");
                sqlQueryCheck.setString(1, email);
                res = sqlQueryCheck.executeQuery();
                
                if(res.next() == false) {
                    JOptionPane.showMessageDialog(this, "Invalid Email");
                } else {
                    jLabel14.setVisible(true);
                    jPanel30.setVisible(true);
                }
            } catch (Exception ex) {
                Logger.getLogger(Page2_ResetPass.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        // Operation of verifying email
        String email = txtEmail.getText();
        
        try {
            // checking if user credential already exist
            Connection conn = DBConnection.setConnection();
            sqlQueryCheck = conn.prepareStatement("select * from tbl_users where email=?");
            sqlQueryCheck.setString(1, email);
            res = sqlQueryCheck.executeQuery();

            if(res.next() == false) {
                JOptionPane.showMessageDialog(this, "Invalid Email");
                
                txtEmail.setText("");
                if(txtEmail.getText().trim().equals("")){
                    txtEmail.setText("someone@newmail.com");
                    txtEmail.setForeground(Color.gray);
                    emailLine.setBackground(Color.black);
                }
            } else {
                // hide this content
                jLabel15.setVisible(false);
                jPanel31.setVisible(false);
                btnVerify.setVisible(false);
                
                // display this content
                jLabel14.setVisible(true);
                jPanel30.setVisible(true);
                btnNext.setVisible(true);
            }
        } catch (Exception ex) {
            Logger.getLogger(Page2_ResetPass.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void txtTypeHereFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTypeHereFocusGained
        // operation that occur when this field is clicked
        if(txtTypeHere.getText().trim().toLowerCase().equals("type here")){
            txtTypeHere.setText("");
            txtTypeHere.setForeground(Color.black);
            quizLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtTypeHereFocusGained

    private void txtTypeHereFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTypeHereFocusLost
        // operation that occur when this field is not clicked
        if(txtTypeHere.getText().trim().equals("") || txtTypeHere.getText().trim().equals("type here")){
            txtTypeHere.setText("type here");
            txtTypeHere.setForeground(Color.gray);
            quizLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtTypeHereFocusLost

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        String getEmail    = txtEmail.getText();
        String getResponse = txtTypeHere.getText();
        
        // checking if any field is empty before submitting the form
        if(getResponse.trim().equals("") || getResponse.trim().equals("type here")){
            JOptionPane.showMessageDialog(this, "fill the answer before you proceed");
            jTabbedPane1.setSelectedIndex(0);
            
            // hide this content
            jLabel15.setVisible(false);
            jPanel31.setVisible(false);
            btnVerify.setVisible(false);

            // display this content
            jLabel14.setVisible(true);
            jPanel30.setVisible(true);
            btnNext.setVisible(true);
        }
        else {
            try {
                // checking if user credential already exist
                Connection conn = DBConnection.setConnection();
                sqlQueryCheck = conn.prepareStatement("select * from tbl_security_quiz where email=? and response=?");
                sqlQueryCheck.setString(1, getEmail);
                sqlQueryCheck.setString(2, getResponse);
                res = sqlQueryCheck.executeQuery();
                
                if(res.next() == true) {
                    jTabbedPane1.setSelectedIndex(1);
            
                    // display this content
                    jLabel22.setVisible(true);
                    jPanel10.setVisible(true);
                    jLabel9.setVisible(true);
                    jPanel8.setVisible(true);
                    btnResetPwd.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid Response");
                    
                    txtTypeHere.setText("");
                    if(txtTypeHere.getText().trim().equals("")){
                        txtTypeHere.setText("type here");
                        txtTypeHere.setForeground(Color.gray);
                        quizLine.setBackground(Color.black);
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(Page1_Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * Form validation
     */
    private void txtNewPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPwdFocusGained
        // operation that occur when this field is clicked
        String pwd = String.valueOf(txtNewPwd.getPassword());   // get the password in text format (not in password/**** format)

        if(pwd.trim().toLowerCase().equals("yourpassword")){
            txtNewPwd.setText("");
            txtNewPwd.setForeground(Color.black);
            PasswordLine1.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtNewPwdFocusGained

    private void txtNewPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPwdFocusLost
        // operation that occur when this field is not clicked
        String pwd = String.valueOf(txtNewPwd.getPassword());   // get the password in text format (not in password/**** format)

        if(pwd.trim().equals("") || pwd.trim().equals("yourpassword")){
            txtNewPwd.setText("yourpassword");
            txtNewPwd.setForeground(Color.gray);
            PasswordLine1.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtNewPwdFocusLost

    private void txtNewPwdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPwdKeyReleased
        String PATTERN = "^[a-zA-Z0-9_!@#$%^&*-?]{10,30}$";
        Pattern patt   = Pattern.compile(PATTERN);
        Matcher match  = patt.matcher(txtNewPwd.getText());

        if(!match.matches()) {
            pwdError1.setText("Invalid Password/Its too short!");
        } else {
            pwdError1.setText(null);
        }
    }//GEN-LAST:event_txtNewPwdKeyReleased

    private void txtConfirmPwdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPwdFocusGained
        // operation that occur when this field is clicked
        String pwd = String.valueOf(txtConfirmPwd.getPassword());   // get the password in text format (not in password/**** format)

        if(pwd.trim().toLowerCase().equals("yourpassword")){
            txtConfirmPwd.setText("");
            txtConfirmPwd.setForeground(Color.black);
            PasswordLine2.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtConfirmPwdFocusGained

    private void txtConfirmPwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPwdFocusLost
        // operation that occur when this field is not clicked
        String pwd = String.valueOf(txtConfirmPwd.getPassword());   // get the password in text format (not in password/**** format)

        if(pwd.trim().equals("") || pwd.trim().equals("yourpassword")){
            txtConfirmPwd.setText("yourpassword");
            txtConfirmPwd.setForeground(Color.gray);
            PasswordLine2.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtConfirmPwdFocusLost

    private void btnResetPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPwdActionPerformed
        // operation of reseting the password
        String userEmail = txtEmail.getText();
        
        String newpwd   = String.valueOf(txtNewPwd.getPassword());
        String confpwd  = String.valueOf(txtConfirmPwd.getPassword());

        // checking if any field is empty before submitting the form
        if(newpwd.trim().equals("") || newpwd.trim().equals("yourpassword")){
            pwdError1.setText("Password is missing!");
        }
        else if(confpwd.trim().equals("") || confpwd.trim().equals("yourpassword")){
            pwdError2.setText("Password is missing!");
        }
        else {  
            try {
                // checking if user credential already exist
                conn = DBConnection.setConnection();
                sqlQueryCheck = conn.prepareStatement("select * from tbl_users where email=?");
                sqlQueryCheck.setString(1, userEmail);
                res = sqlQueryCheck.executeQuery();
            
                // if email is in the database then Proceed
                if(res.next()){
                    // checking if new password is same as confirm password
                    if (newpwd.equals(confpwd)) {
                        // update the password in the database
                        sqlQueryUpdate = conn.prepareStatement("update tbl_users SET password=? WHERE email=? ");
                        sqlQueryUpdate.setString(1, newpwd);
                        sqlQueryUpdate.setString(2, userEmail);
                        
                        if (sqlQueryUpdate.executeUpdate() != 0) {
                            // Show success mesage
                            JOptionPane.showMessageDialog(this, "You have reset your Password successfully.");

                            txtNewPwd.setText("yourpassword");
                            txtConfirmPwd.setText("yourpassword");

                            // redirect the user to login page
                            new Page1_Login().setVisible(true);
                            this.dispose();

                            return;
                        }
                    }
                    else {
                        JOptionPane.showMessageDialog(this, "Confirm Password doesn't match with new Password!");
                        txtConfirmPwd.setText("");

                        txtConfirmPwd.requestFocus();
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(Page6_Settings.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnResetPwdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // redirect to login
        Page1_Login login = new Page1_Login();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page2_ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page2_ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page2_ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page2_ResetPass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page2_ResetPass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PasswordLine1;
    private javax.swing.JLabel PasswordLine2;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnResetPwd;
    private javax.swing.JButton btnVerify;
    private javax.swing.JTextField emailLine;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel pwdError1;
    private javax.swing.JLabel pwdError2;
    private javax.swing.JTextField quizLine;
    private javax.swing.JPasswordField txtConfirmPwd;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtNewPwd;
    private javax.swing.JTextField txtTypeHere;
    // End of variables declaration//GEN-END:variables
}