/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import DB.DBConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JoeAlpha
 */
public class Page4_SecurityQuiz extends javax.swing.JFrame {

    /**
     * Creates new form Page1_Login
     */
    public Page4_SecurityQuiz() {
        initComponents();
        
        // center the form
        this.setLocationRelativeTo(this);
    }
    
    // create a variable for connection to the database     
    PreparedStatement sqlQueryCheck; 
    PreparedStatement sqlQueryInsert;    
    PreparedStatement sqlQueryLogin;
    ResultSet res;    
    Connection conn;

    Page4_SecurityQuiz(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        responseLine = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtResponse = new javax.swing.JTextField();
        jPanel31 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSecurityQuiz = new javax.swing.JTextArea();
        jPanel32 = new javax.swing.JPanel();
        emailLine = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSaveResponse = new javax.swing.JButton();
        lblExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setOpaque(false);
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cover page.png"))); // NOI18N
        jPanel27.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 320, 320));

        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 340, 320));

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setOpaque(false);
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 20)); // NOI18N
        jLabel2.setForeground(java.awt.SystemColor.textHighlight);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Java Authentication System");
        jPanel28.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 350, 50));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Security Question");
        jPanel28.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 350, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(java.awt.SystemColor.windowBorder);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Answer provided will be used to reset your password");
        jPanel28.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 350, -1));

        jPanel30.setOpaque(false);
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        responseLine.setBackground(java.awt.Color.darkGray);
        responseLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel30.add(responseLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 280, 1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/list.png"))); // NOI18N
        jPanel30.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 30, 38));

        txtResponse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtResponse.setForeground(java.awt.Color.gray);
        txtResponse.setText("year month");
        txtResponse.setBorder(null);
        txtResponse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtResponseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtResponseFocusLost(evt);
            }
        });
        jPanel30.add(txtResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, 220, 40));

        jPanel28.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 245, 280, 50));

        jPanel31.setOpaque(false);
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSecurityQuiz.setEditable(false);
        txtSecurityQuiz.setColumns(20);
        txtSecurityQuiz.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSecurityQuiz.setLineWrap(true);
        txtSecurityQuiz.setRows(5);
        txtSecurityQuiz.setText("Which year and month were you born");
        txtSecurityQuiz.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 1, 1));
        jScrollPane1.setViewportView(txtSecurityQuiz);

        jPanel31.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 90));

        jPanel28.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 145, -1, 100));

        jPanel32.setOpaque(false);
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emailLine.setBackground(java.awt.Color.darkGray);
        emailLine.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel32.add(emailLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 280, 1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Email Icon.png"))); // NOI18N
        jPanel32.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 30, 38));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setForeground(java.awt.Color.gray);
        txtEmail.setText("someone@newmail.com");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel32.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 0, 220, 40));

        jPanel28.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 280, 50));

        btnSaveResponse.setBackground(java.awt.SystemColor.textHighlight);
        btnSaveResponse.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSaveResponse.setForeground(java.awt.Color.white);
        btnSaveResponse.setText("Save");
        btnSaveResponse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveResponseActionPerformed(evt);
            }
        });
        jPanel28.add(btnSaveResponse, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 303, 110, 30));

        jPanel26.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 350, 340));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setOpaque(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel26.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 1, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // exit the system
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        lblExit.setForeground(Color.white);
        lblExit.setBackground(Color.red);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        lblExit.setForeground(Color.black);
        lblExit.setBackground(Color.white);
    }//GEN-LAST:event_lblExitMouseExited

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // operation that occur when this field is clicked
        if(txtEmail.getText().trim().toLowerCase().equals("someone@newmail.com")){
            txtEmail.setText("");
            txtEmail.setForeground(Color.black);
            emailLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // operation that occur when this field is not clicked
        if(txtEmail.getText().trim().equals("") || txtEmail.getText().trim().equals("someone@newmail.com")){
            txtEmail.setText("someone@newmail.com");
            txtEmail.setForeground(Color.gray);
            emailLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtResponseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtResponseFocusGained
        // operation that occur when this field is clicked
        if(txtResponse.getText().trim().toLowerCase().equals("year month")){
            txtResponse.setText("");
            txtResponse.setForeground(Color.black);
            responseLine.setBackground(new Color(0,102,255));
        }
    }//GEN-LAST:event_txtResponseFocusGained

    private void txtResponseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtResponseFocusLost
        // operation that occur when this field is not clicked
        if(txtResponse.getText().trim().equals("") || txtResponse.getText().trim().equals("year month")){
            txtResponse.setText("year month");
            txtResponse.setForeground(Color.gray);
            responseLine.setBackground(Color.black);
        }
    }//GEN-LAST:event_txtResponseFocusLost

    private void btnSaveResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveResponseActionPerformed
        // operation of saving the response
        String securityEmail    = txtEmail.getText();
        String securityQuiz     = txtSecurityQuiz.getText();
        String securityResponse = txtResponse.getText();
        
        // checking if any field is empty before submitting the form
        if(securityEmail.trim().equals("") || securityEmail.trim().equals("someone@newmail.com")){
            JOptionPane.showMessageDialog(null, "You have not given your Email !");
        } 
        else if(securityResponse.trim().equals("") || securityResponse.trim().equals("year month")){
            JOptionPane.showMessageDialog(null, "You have not Responded to the Quiz !");
        }
        else {
            try {
                // validate the email provided
                Connection conn = DBConnection.setConnection();
                sqlQueryCheck = conn.prepareStatement("select * from tbl_users where email=?");
                sqlQueryCheck.setString(1, securityEmail);
                res = sqlQueryCheck.executeQuery();
                
                if(!res.isBeforeFirst()) {
                    // if the email dont match with the one in the database
                    JOptionPane.showMessageDialog(this, "Invalid Email", "Please Try again", JOptionPane.ERROR_MESSAGE);

                    // clearing the neccessary field to allow the user to key in valid Cridentials  
                    txtEmail.setText(""); 
                    txtEmail.requestFocus();
                    return;     
                } else {
                    sqlQueryInsert = conn.prepareStatement("insert into tbl_security_quiz (email,quiz,response) values (?,?,?) ");
                    sqlQueryInsert.setString(1, securityEmail);
                    sqlQueryInsert.setString(2, securityQuiz);
                    sqlQueryInsert.setString(3, securityResponse);

                    //if the record is inserted successfully the state of executeUpdate() will be 1
                    if (sqlQueryInsert.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "Your respons has been saved successfully.");
                        JOptionPane.showMessageDialog(null, "you will use it to reset your password");

                        // clearing the form 
                        txtEmail.setText("");
                        txtSecurityQuiz.setText("");
                        txtResponse.setText("");

                        // redirect the user to login page
                        new Page1_Login().setVisible(true);
                        this.dispose();

                        return;
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(Page4_SecurityQuiz.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
    }//GEN-LAST:event_btnSaveResponseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page4_SecurityQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page4_SecurityQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page4_SecurityQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page4_SecurityQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page4_SecurityQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveResponse;
    private javax.swing.JTextField emailLine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JTextField responseLine;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtResponse;
    private javax.swing.JTextArea txtSecurityQuiz;
    // End of variables declaration//GEN-END:variables
}